import exceptions
print(exceptions.greet("Students"))
